/**
 * actionsType 表示系统中所有的修改数据指令名称
 * @type {string}
 */
const SELECT_MENU = 'SELECT_MENU';

const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';
const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
const ADD_ARTICLE='ADD_ARTICLE';
const UPDATE_ARTICLE='UPDATE_ARTICLE';
const REMOVE_ARTICLE='REMOVE_ARTICLE';

export {
    SELECT_MENU,

    GET_ARTICLE_LIST,
    GET_ARTICLE_DETAIL,
    ADD_ARTICLE,
    UPDATE_ARTICLE,
    REMOVE_ARTICLE
};
